install.packages("e1071")
library(raster)
library(cluster)
library(rgdal)
library(RStoolbox)
library(randomForest)
library(e1071)
band_1 <- raster('/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Digital Image Analysis and GIS/Data/Landsat Data/LT51930272003195MTI01_B1.TIF')
band_2 <- raster('/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Digital Image Analysis and GIS/Data/Landsat Data/LT51930272003195MTI01_B2.TIF')
band_3 <- raster('/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Digital Image Analysis and GIS/Data/Landsat Data/LT51930272003195MTI01_B3.TIF')
band_4 <- raster('/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Digital Image Analysis and GIS/Data/Landsat Data/LT51930272003195MTI01_B4.TIF')
band_5 <- raster('/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Digital Image Analysis and GIS/Data/Landsat Data/LT51930272003195MTI01_B5.TIF')
band_6 <- raster('/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Digital Image Analysis and GIS/Data/Landsat Data/LT51930272003195MTI01_B6.TIF')
band_7 <- raster('/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Digital Image Analysis and GIS/Data/Landsat Data/LT51930272003195MTI01_B7.TIF')

lsat_allbands <- stack(band_1,band_2,band_3,band_4,band_5,band_6,band_7)
plot(lsat_allbands,1)
ext <- drawExtent()
lsat_allbands_crop <- crop(lsat_allbands,ext)
plot(lsat_allbands_crop,1)

writeRaster(lsat_allbands_crop,"/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Digital Image Analysis and GIS/Data/Landsat Data/landsat_allbands_rasterext.TIF")

td <- rgdal::readOGR("/Users/Marina/Documents/Universität/Uni Würzburg/1. Semester/Programming and Geostatistical Analysis/Project_R/vector_data","Training_areas")

class1 <- superClass(lsat_allbands_crop,trainData = td,responseCol = "Class")
class1
install.packages("maptools")
library(maptools)
plot(class1$map)
